#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Add all changes
git add .

# Get the current branch name
BRANCH_NAME=$(git symbolic-ref --short HEAD)

# Create commit message based on staged files
COMMIT_MSG="auto: update $(git diff --cached --name-only | tr '\n' ' ')"

# Commit changes
git commit -m "$COMMIT_MSG" || true

# Push to the current branch
git push origin $BRANCH_NAME || true
